[project]
name = "cmpsc105-lab04"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.5",
    "seaborn>=0.13.2",
]

[project.scripts]
cmpsc105-lab04 = "cmpsc105_lab04:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
